[package]
name = "ktm-docs"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.108"
web-sys = { version = "0.3.85", features = [ "console", "Window", "Document", "HtmlElement", "Element", "MediaQueryList", "MediaQueryListEvent" ] }
leptos = { version = "0.8.15", features = ["csr"] }
stylist = "0.13.0"
pulldown-cmark = "0.13.0"